YOffset=300; // no quotes!!
XOffset=0;
staticYOffset=30; // no quotes!!
slideSpeed=20 // no quotes!!
waitTime=100; // no quotes!! this sets the time the menu stays out for after the mouse goes off it.
menuBGColor="#757575";
menuIsStatic="yes"; //this sets whether menu should stay static on the screen
menuWidth=150; // Must be a multiple of 10! no quotes!!
menuCols=2;
hdrFontFamily="Tahoma";
hdrFontSize="2";
hdrFontColor="white";
hdrBGColor="#757575";
hdrAlign="left";
hdrVAlign="center";
hdrHeight="19";
linkFontFamily="Tahoma";
linkFontSize="2";
linkBGColor="white";
linkOverBGColor="#FFFF99";
linkTarget="_top";
linkAlign="Left";
barBGColor="#757575";
barFontFamily="Tahoma";
barFontSize="2";
barFontColor="white";
barVAlign="center";
barWidth=20; // no quotes!!
barText="메 뉴"; // <IMG> tag supported. Put exact html for an image to show.

// ssmItems[...]=[name, link, target, colspan, endrow?] - leave 'link' and 'target' blank to make a header
ssmItems[0]=["설치하기"] //create header
//ssmItems[1]=["제품의 특징", "ch02s01.htm",""]//
ssmItems[1]=["구성품 확인", "ch02s01.htm",""]
ssmItems[2]=["Mechanical Layout (400UT(N))", "ch02s02.htm", ""]
ssmItems[3]=["Mechanical Layout (460UT(N))", "ch02s03.htm", ""]
ssmItems[4]=["컴퓨터와 연결하기", "ch02s04.htm", ""]
ssmItems[5]=["AV 장치와 연결하기", "ch02s05.htm", ""]
ssmItems[6]=["DVD 플레이어와 연결하기", "ch02s06.htm", ""]
ssmItems[7]=["DTV 셋톱박스 연결하기", "ch02s07.htm", ""]
ssmItems[8]=["HDMI 연결 사용", "ch02s08.htm", ""]
ssmItems[9]=["DVI - HDMI 케이블로 연결", "ch02s09.htm", ""]
ssmItems[10]=["오디오 시스템 연결하기", "ch02s10.htm", ""]
ssmItems[11]=["LAN 케이블 연결하기", "ch02s11.htm", ""]
ssmItems[12]=["USB 연결하기", "ch02s12.htm", ""]
ssmItems[13]=["도난 방지용 잠금 장치", "ch02s13.htm", ""]							
ssmItems[14]=["빠른 메뉴"] //create header
ssmItems[15]=["TOP", "#top", "_self"]

//ssmItems[6]=["Language", "../../../monsetup.htm", ""]

buildMenu();