
// Generated by Easy HTML To Any Script Converter
// 2, 5 Layer popup
document.writeln("<div id=\"magic\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=magic; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"#ffffff\">");
document.writeln("			");
document.writeln("			MagicBright&trade;");
document.writeln("			");
document.writeln("			<\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'magic\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clmagic\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clmagic\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'magic\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/magic.gif\" border=\"0\"><\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("        <div id=\"Brightness\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Brightness; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Brightness");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Brightness\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clBrightness\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clBrightness\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Brightness\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/bright.gif\" border=\"0\"><\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("");
document.writeln("		<div id=\"Auto\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Auto; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			AUTO");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Auto\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clAuto\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clAuto\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Auto\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/Auto.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"Cont\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Cont; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Contrast");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Cont\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clCont\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clCont\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Cont\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/Contrast.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"Tone\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Tone; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Color Tone");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Tone\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'Tone\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clTone\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Tone\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/Tone.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"Control\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Control; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Color Control");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Control\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clControl\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clControl\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Control\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/control.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"Shar\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Shar; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Sharpness");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Shar\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clShar\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clShar\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Shar\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/Sharpness.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"magic_1\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=magic_1; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			MagicColor");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'magic_1\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clmagic_1\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clmagic_1\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'magic_1\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/magic_1.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"magic_2\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=magic_2; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Color Effect");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'magic_2\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clmagic_2\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clmagic_2\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'magic_2\'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/magic_2.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"magic_3\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=magic_3; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Image Size");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'magic_3\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clmagic_3\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clmagic_3\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'magic_3'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/magic_3.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"effect\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=effect; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Color Effect");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'effect\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'cleffect\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"cleffect\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'effect'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/effect.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");
document.writeln("		<div id=\"Source\" style=\"display:none;position:absolute;width:400\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"400\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Source; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			SOURCE");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Source\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clSource\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clSource\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"400\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"400\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Source'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/source.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");


document.writeln("		<div id=\"Infor\" style=\"display:none;position:absolute;width:352\">");
document.writeln("		<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" bgcolor=\"white\" width=\"352\" align=\"center\">");
document.writeln("		<tr>");
document.writeln("			<td background=\"../../_IMG/Common/all/TRBG.GIF\" onMouseOut=\"drag=0\" onMouseOver=\"dragObj=Infor; drag=1;\" title=\"Drag\" valign=\"middle\" align=\"center\" width=\"400\"><font color=\"ffffff\">");
document.writeln("			");
document.writeln("			Information");
document.writeln("			");
document.writeln("			<\/font><\/td>");
document.writeln("			<td valign=\"middle\" align=\"center\" width=\"28\"><a href=\"#\" onClick=\"hide(\'Infor\'); return false\" title=\"Close\" onMouseOut=\"MM_swapImgRestore()\" onMouseOver=\"MM_swapImage(\'clInfor\',\'\',\'../../_IMG/Common/all/pclose02.gif\',1)\"><img src=\"../../_IMG/Common/all/pclose01.GIF\" border=\"0\" name=\"clInfor\" align=\"absmiddle\"><\/a><\/td>");
document.writeln("		<\/tr>");
document.writeln("		<tr>");
document.writeln("			<td bgcolor=\"black\" height=\"3\" colspan=\"2\" width=\"352\"><\/td>");
document.writeln("		<\/tr> ");
document.writeln("		<tr>");
document.writeln("			<td colspan=\"2\" width=\"352\">");
document.writeln("				<table cellspacing=\"0\" cellpadding=\"0\" border=\"1\" bordercolor=\"black\"><tr><td>");
document.writeln("				");
document.writeln("				<a href=\"#osd_hide\" onClick=\"hide(\'Infor'); return false\">");
document.writeln("				<img src=\"../../_IMG/Lang/eng/osd/direct/Infor.gif\" border=\"0\">");
document.writeln("				<\/a>");
document.writeln("				<\/td><\/tr><\/table>");
document.writeln("			<\/td>");
document.writeln("		<\/tr>");
document.writeln("		<\/table>");
document.writeln("		<\/div>");
document.writeln("");


document.writeln("<OBJECT ID=\"launch\" CLASSID=\"CLSID:A6616B31-4860-41E2-98E3-CA7649AF172F\" width=0 height=0></OBJECT>");



// 2, 5 Layer Popup End ---------------------------------------------------------------------



// PDF Link ----------------------------------------------------------------------------------
function OpenPDF_bul() {
      window.open("../../_PDF/BN59-00910H-00Bul.pdf", "_blank") ;
}

function OpenPDF_cro() {
      window.open("../../_PDF/BN59-00910H-00Cro.pdf", "_blank") ;
}

function OpenPDF_cze() {
      window.open("../../_PDF/BN59-00910H-00Cze.pdf", "_blank") ;
}

function OpenPDF_dan() {
      window.open("../../_PDF/BN59-00910H-00Dan.pdf", "_blank") ;
}

function OpenPDF_dut() {
      window.open("../../_PDF/BN59-00910H-00Dut.pdf", "_blank") ;
}

function OpenPDF_eng() {
      window.open("../../_PDF/BN59-00910H-00Eng.pdf", "_blank") ;
}

function OpenPDF_est() {
      window.open("../../_PDF/BN59-00910H-00Est.pdf", "_blank") ;
}

function OpenPDF_fin() {
      window.open("../../_PDF/BN59-00910H-00Fin.pdf", "_blank") ;
}

function OpenPDF_fre() {
      window.open("../../_PDF/BN59-00910H-00Fre.pdf", "_blank") ;
}

function OpenPDF_ger() {
      window.open("../../_PDF/BN59-00910H-00Ger.pdf", "_blank") ;
}

function OpenPDF_gre() {
      window.open("../../_PDF/BN59-00910H-00Gre.pdf", "_blank") ;
}

function OpenPDF_hun() {
      window.open("../../_PDF/BN59-00910H-00Hun.pdf", "_blank") ;
}

function OpenPDF_ita() {
      window.open("../../_PDF/BN59-00910H-00Ita.pdf", "_blank") ;
}

function OpenPDF_jap() {
      window.open("../../_PDF/BN59-00910H-00Jap.pdf", "_blank") ;
}

function OpenPDF_kor() {
      window.open("../../_PDF/BN59-00910H-00Kor.pdf", "_blank") ;
}

function OpenPDF_lat() {
      window.open("../../_PDF/BN59-00910H-00Lat.pdf", "_blank") ;
}

function OpenPDF_lit() {
      window.open("../../_PDF/BN59-00910H-00Lit.pdf", "_blank") ;
}

function OpenPDF_nor() {
      window.open("../../_PDF/BN59-00910H-00Nor.pdf", "_blank") ;
}

function OpenPDF_pol() {
      window.open("../../_PDF/BN59-00910H-00Pol.pdf", "_blank") ;
}

function OpenPDF_por() {
      window.open("../../_PDF/BN59-00910H-00Por.pdf", "_blank") ;
}

function OpenPDF_rom() {
      window.open("../../_PDF/BN59-00910H-00Rom.pdf", "_blank") ;
}

function OpenPDF_rus() {
      window.open("../../_PDF/BN59-00910H-00Rus.pdf", "_blank") ;
}

function OpenPDF_sc() {
      window.open("../../_PDF/BN59-00910H-00SC.pdf", "_blank") ;
}

function OpenPDF_ser() {
      window.open("../../_PDF/BN59-00910H-00Ser.pdf", "_blank") ;
}

function OpenPDF_slk() {
      window.open("../../_PDF/BN59-00910H-00Slk.pdf", "_blank") ;
}

function OpenPDF_sln() {
      window.open("../../_PDF/BN59-00910H-00Sln.pdf", "_blank") ;
}

function OpenPDF_spa() {
      window.open("../../_PDF/BN59-00910H-00Spa.pdf", "_blank") ;
}

function OpenPDF_swe() {
      window.open("../../_PDF/BN59-00910H-00Swe.pdf", "_blank") ;
}

function OpenPDF_tc() {
      window.open("../../_PDF/BN59-00910H-00TC.pdf", "_blank") ;
}

function OpenPDF_tur() {
      window.open("../../_PDF/BN59-00910H-00Tur.pdf", "_blank") ;
}

function OpenPDF_ukr() {
      window.open("../../_PDF/BN59-00910H-00Ukr.pdf", "_blank") ;
}

function OpenPDF_vie() {
      window.open("../../_PDF/BN59-00910H-00Vie.pdf", "_blank") ;
}




 // jjol2

if (isNS4)
{
	var divMenu = document["divMenu"];
	divMenu.top = top.pageYOffset + 100;
	divMenu.visibility = "visible";
	moveRightEdge();

}
else if (isDOM)
{
	var divMenu = getRef('divMenu');
	divMenu.style.top = (isNS ? window.pageYOffset : document.body.scrollTop) + 80;
	divMenu.style.visibility = "visible";
	moveRightEdge();
}

