str  = ''


str += '<table width="123" border="0" cellspacing="0" cellpadding="0">'
            str += '<tr>'
              str += '<td height="34" colspan="3" background="../../_IMG/Common/all/top.jpg">&nbsp;</td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td width="3" rowspan="8" background="../../_IMG/Common/all/left.jpg">&nbsp;</td>'
              str += '<td  class="bold_color4"><p style="margin-left:10px"><a href="javascript:MagicTune()">MagicTune</a><br></td>'
              str += '<td width="3" rowspan="8" background="../../_IMG/Common/all/right.jpg">&nbsp;</td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="1" background="../../_IMG/Common/all/line_dot.gif"></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="1" background="../../_IMG/Common/all/line_dot.gif"></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td class="bold_color4"><p style="margin-left:10px"><a href="javascript:natural()">Natural Color</a><br></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="1" background="../../_IMG/Common/all/line_dot.gif"></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td class="bold_color4"><p style="margin-left:10px"><a href="javascript:drive()">Monitor Driver</a><br></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="1" background="../../_IMG/Common/all/line_dot.gif"></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td class="bold_color4"><p style="margin-left:10px"><a href="javascript:ie_reader()">Acrobat Reader</a><br></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="1" background="../../_IMG/Common/all/line_dot.gif"></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="1" background="../../_IMG/Common/all/line_dot.gif"></td>'
            str += '</tr>'
            str += '<tr>'
              str += '<td height="12" colspan="3" background="../../_IMG/Common/all/bottom.gif"></td>'
            str += '</tr>'
        str += '</table>'

document.write( str );